export const ERROR_CODE = Object.freeze({
  INVALID_REQUEST: "INVALID_REQUEST",
  INVALID_USERNAME: "INVALID_USERNAME",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  INVALID_DISPLAY_NAME: "INVALID_DISPLAY_NAME",
  USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  TOKEN_REQUIRED: "TOKEN_REQUIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  AUTH_DB_NOT_READY: "AUTH_DB_NOT_READY",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
});
